apiVersion: v1
kind: Namespace
metadata:
  name: harness-relay-proxy

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: relay-proxy-configs
  namespace: harness-relay-proxy
data:
  ACCOUNT_IDENTIFIER: REPLACE_ACC
  ORG_IDENTIFIER: REPLACE_ORG
  ADMIN_SERVICE_TOKEN: REPLACE_PAT
  API_KEYS: REPLACE_ENV_SDK_TOKEN
  AUTH_SECRET: secret
  DEBUG: "false"
  OFFLINE: "false"
  PORT: "7000"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: harness-relay-proxy
  name: harness-relay-proxy
  namespace: harness-relay-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harness-relay-proxy
  template:
    metadata:
      labels:
        app: harness-relay-proxy
    spec:
      containers:
      - image: harness/ff-proxy:1.0.2
        name: ff-proxy
        envFrom:
        - configMapRef:
            name: relay-proxy-configs

---

apiVersion: v1
kind: Service
metadata:
  name: harness-relay-proxy-svc
  namespace: harness-relay-proxy
spec:
  type: NodePort
  selector:
    app: harness-relay-proxy
  ports:
    - port: 7000
      targetPort: 7000
      nodePort: 30070
